# Generated by Django 3.1.5 on 2021-02-01 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя организации')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumingOtoplenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.FloatField(default=0)),
                ('limit', models.FloatField(default=0)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upravlenie.adress', verbose_name='Адрес')),
            ],
            managers=[
                ('otklonenie', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='adress',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upravlenie.organization', verbose_name='Организация'),
        ),
    ]
