# Generated by Django 3.1.5 on 2021-02-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upravlenie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consumingotoplenie',
            managers=[
            ],
        ),
    ]
