# Generated by Django 3.1.5 on 2021-02-01 08:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('upravlenie', '0002_auto_20210201_1528'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consumingotoplenie',
            managers=[
                ('otklonenie', django.db.models.manager.Manager()),
            ],
        ),
    ]
