# Generated by Django 3.1.5 on 2021-02-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upravlenie', '0003_auto_20210201_1533'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consumingotoplenie',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='consumingotoplenie',
            name='otklonenie',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
