# Generated by Django 3.1.5 on 2021-02-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upravlenie', '0004_auto_20210201_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumingotoplenie',
            name='otklonenie',
            field=models.FloatField(editable=False),
        ),
    ]
