# Generated by Django 3.1.5 on 2021-02-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upravlenie', '0007_auto_20210201_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumingotoplenie',
            name='otklonenie',
        ),
    ]
